name: macOS Android Tester

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 360
    steps:
      - name: "1. Descargar repositorio"
        uses: actions/checkout@v4

      - name: "2. Instalar Tailscale"
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: "3. Conectar Tailscale"
        run: |
          sudo tailscale up --authkey=tskey-auth-kBU3f1HEM721CNTRL-ZwRrWsEkEhLYV6GgDopDhL6hKCgVjrDs --hostname=github-macos
          echo "✅ Tailscale conectado: $(tailscale ip -4)"

      - name: "4. Iniciar sesión interactiva con tmate"
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      - name: "5. Guardar cambios"
        if: always()
        run: |
          git config --global user.name 'GitHub Actions macOS'
          git config --global user.email 'actions@github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Guardado desde macOS" && git push
          fi
